'use strict';

module.exports = {
  SEARCH: "MAIL_SEARCH",
  SEARCH_SUCCESS: "MAIL_SEARCH_SUCCESS",

  DESTROY: "MAIL_DESTROY",
  DESTROY_SUCCESS: "MAIL_DESTROY_SUCCESS",

  READ: "MAIL_READ",
  READ_SUCCESS: "MAIL_READ_SUCCESS",

  UNREAD: "MAIL_UNREAD",
  UNREAD_SUCCESS: "MAIL_UNREAD_SUCCESS",

  TOGGLE_HIGHLIGHT: "MAIL_TOGGLE_HIGHLIGHT",
  TOGGLE_HIGHLIGHT_SUCCESS: "MAIL_TOGGLE_HIGHLIGHT_SUCCESS",
};
