'use strict';

module.exports = {
  SHOW: "MAIL_SHOW",

  SEARCH: "MAIL_SEARCH",
  SEARCH_SUCCESS: "MAIL_SEARCH_SUCCESS",

  REMOVE_FROM_CATEGORY: "MAIL_REMOVE_FROM_CATEGORY",
  REMOVE_FROM_CATEGORY_SUCCESS: "MAIL_REMOVE_FROM_CATEGORY_SUCCESS",

  READ: "MAIL_READ",
  READ_SUCCESS: "MAIL_READ_SUCCESS",

  UNREAD: "MAIL_UNREAD",
  UNREAD_SUCCESS: "MAIL_UNREAD_SUCCESS",

  TOGGLE_HIGHLIGHT: "MAIL_TOGGLE_HIGHLIGHT",
  TOGGLE_HIGHLIGHT_SUCCESS: "MAIL_TOGGLE_HIGHLIGHT_SUCCESS",
};
